apiVersion: v1
kind: ConfigMap
metadata:
  name: django-demo-config
  namespace: django-demo
  labels:
    app.kubernetes.io/name: django-demo
    app.kubernetes.io/component: web
data:
  DJANGO_DEBUG: "false"
  DJANGO_ALLOWED_HOSTS: "django-demo.k3s.home.verrve.ru,django-demo.local,localhost,127.0.0.1"
  ALLOWED_HOSTS: "django-demo.k3s.home.verrve.ru,django-demo.local,localhost,127.0.0.1"
  PORT: "8000"
