apiVersion: v1
kind: Secret
metadata:
  name: django-demo-tls
  namespace: django-demo
  labels:
    app.kubernetes.io/name: django-demo
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    PASTE_FULLCHAIN_OR_CERTIFICATE_HERE
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    PASTE_PRIVATE_KEY_HERE
    -----END PRIVATE KEY-----
